version: "3"

networks:
  kibana:
    driver: bridge
  log_stash:
    driver: bridge

services:
  elasticsearch:
    image: docker.io/elasticsearch:latest
    container_name: es-local
    hostname: es-local
    networks:
      - log_stash
      - kibana
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "TZ=Asia/Shanghai"
    restart: unless-stopped
  kibana:
    image: docker.io/kibana:latest
    container_name: kb-local
    hostname: kb-local
    networks:
      - kibana
    ports:
      - 5601:5601
    restart: unless-stopped
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - kibana
  logstash:
    image: docker.io/logstash:latest
    container_name: logstash-filebeat
    hostname: logstash-filebeat
    networks:
      - log_stash
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5044:5044
    privileged: true
    volumes:
      - ./logstash_settings:/config-dir
    command: logstash -f /config-dir/logstash-filebeat-sample.conf
    depends_on:
      - elasticsearch
    environment:
      - "TZ=Asia/Shanghai"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
    labels:
      production_status: "testing"
