version: '2'
services:
  nginx001: 
    #image: dev-nginx:0.0.1
    image: docker.io/nginx:latest
    container_name: dev-nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
    links: 
      - tomcat001:t01 
      - tomcat002:t02
    ports: 
      - "80:80" 
    restart: always 
  tomcat001: 
    image: docker.io/tomcat:latest
    container_name: dev-tomcat-8081
    ports: 
      - "8081:8080"
    environment:
      TOMCAT_SERVER_ID: tomcat_server_001
    restart: always
  tomcat002: 
    image: docker.io/tomcat:latest
    container_name: dev-tomcat-8082
    ports: 
      - "8082:8080"
    environment:
      TOMCAT_SERVER_ID: tomcat_server_002
    restart: always
