version: "3"
services:
  postgres:
    image: docker.io/postgres
    privileged: true
    container_name: local_postgresql
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
