version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: my_gitlab
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "8822:22"
    volumes:
      - ./data/gitlab/data:/var/opt/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/config:/etc/gitlab
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.146.128'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.aliyun.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "kimasd102419@aliyun.com"
        gitlab_rails['smtp_password'] = "axbc1kof"
        gitlab_rails['smtp_domain'] = "aliyun.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'kimasd102419@aliyun.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
