version: '2'
services:
  mysql:
#    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: test
      MYSQL_PASS: 123
      MYSQL_ROOT_HOST: '%'
    image: docker.io/mysql:latest 
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    container_name: local-mysql
    restart: always
    volumes:
      #- ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      #- ./init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
      - 33060:33060
