version: '2'
services:
  mysql:
#  network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: test
      MYSQL_PASS: 123
    image: docker.io/mysql:latest 
    container_name: local-mysql
    restart: always
    volumes:
      #- ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
